nav:
  logo: null
  display_title: true
  fixed: true
menu:
  首页: / || fas fa-home
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友链: /link/ || fas fa-link
code_blocks:
  theme: light
  macStyle: false
  height_limit: false
  word_wrap: false
  copy: true
  language: true
  shrink: false
  fullpage: false
social:
  fas fa-home-alt: https://www.rumbl.top || Home
  fab fa-github: https://github.com/bilirumble || Github
  fas fa-envelope: mailto:bilirumble@outlook.com || EMail
favicon: /assets/images/common/favicon.ico
avatar:
  img: /assets/images/common/avatar.jpg
  effect: false
disable_top_img: false
default_top_img: https://api.dujin.org/bing/1920.php
index_img: https://api.dujin.org/bing/1920.php
archive_img: null
tag_img: null
tag_per_img: null
category_img: null
category_per_img: null
footer_img: false
background: null
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:
    - https://i.loli.net/2020/05/01/gkihqEjXxJ5UZ1C.jpg
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg
error_404:
  enable: false
  subtitle: Page Not Found
  background: /img/error-page.png
post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: false
    label: true
  post:
    position: center
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true
index_site_info_top: null
index_top_img_height: null
subtitle:
  enable: true
  effect: true
  typed_option: null
  source: 1
  sub: null
index_layout: 3
index_post_content:
  method: 3
  length: 500
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true
post_copyright:
  enable: true
  decode: false
  author_href: https://www.rumbl.top
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
reward:
  enable: false
  text: null
  QR_code: null
post_edit:
  enable: true
  url: https://github.com/bilirumble/blog/edit/master/source/
related_post:
  enable: true
  limit: 6
  date_type: created
post_pagination: 1
noticeOutdate:
  enable: true
  style: flat
  limit_day: 365
  position: top
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.
footer:
  owner:
    enable: true
    since: 2019
    link: https://www.rumbl.top
  startDate: 2019-08-25 14:35:24
  # 备案
  icp:
    enable: true
    number: 萌ICP备20240013号
    link: https://icp.gov.moe/?keyword=20240013
  # 自定义链接
  links:
    - MoratoMC || https://github.com/MoratoMC
    - Morato || https://www.morato.top
aside:
  enable: true
  hide: false
  button: false
  mobile: false
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: 我是谁，我在哪，我在干什么?
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/bilirumble
  card_announcement:
    enable: true
    content: 呱! 没有公告哦~
  card_recent_post:
    enable: true
    limit: 5
    sort: updated
    sort_order: null
  card_newest_comments:
    enable: false
    sort_order: null
    limit: 6
    storage: 10
    avatar: true
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order: null
  card_tags:
    enable: true
    limit: 40
    color: false
    orderby: random
    order: 1
    sort_order: null
  card_archives:
    enable: true
    type: monthly
    format: YYYY年MM月
    order: -1
    limit: 8
    sort_order: null
  card_post_series:
    enable: true
    series_title: false
    orderBy: date
    order: -1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: null
    runtime_date: true
rightside_bottom: false
translate:
  enable: true
  default: 繁
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: 繁
  msgToSimplifiedChinese: 簡
readmode: true
darkmode:
  enable: true
  button: true
  autoChangeMode: true
  start: '19:00'
  end: '5:00'
rightside_scroll_percent: false
rightside_item_order:
  enable: false
  hide: null
  show: null
anchor:
  auto_update: true
  click_to_scroll: true
photofigcaption: false
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 150
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
math:
  use: katex
  per_page: true
  hide_scrollbar: false
  mathjax:
    enableMenu: true
    tags: none
  katex:
    copy_tex: true
search:
  use: local_search
  placeholder: Search...
  algolia_search:
    hitsPerPage: 6
  local_search:
    preload: true
    top_n_per_article: 1
    unescape: false
    CDN: null
  docsearch:
    appId: null
    apiKey: null
    indexName: null
    option: null
share:
  use: sharejs
  sharejs:
    sites: facebook,twitter,wechat,weibo,qq
  addtoany:
    item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link
comments:
  use: Gitalk
  text: true
  lazyload: false
  count: true
  card_post_count: true
disqus:
  shortname: null
  apikey: null
disqusjs:
  shortname: null
  apikey: null
  option: null
livere:
  uid: null
gitalk:
  client_id: f7e15eac4ef4ca140772
  repo: blog
  owner: bilirumble
  admin: bilirumble
  language: zh-CN
  per_page: 25
  distractionFreeMode: false
  pagerDirection: last
  createIssueManually: false
  proxy: https://cs.rumbl.top/github_access_token
  option:
    proxy: https://cs.rumbl.top/github_access_token
valine:
  appId: null
  appKey: null
  avatar: monsterid
  serverURLs: null
  bg: null
  visitor: false
  option: null
waline:
  serverURL: null
  bg: null
  pageview: false
  option: null
utterances:
  repo: null
  issue_term: pathname
  light_theme: github-light
  dark_theme: photon-dark
  js: null
  option: null
facebook_comments:
  app_id: null
  user_id: null
  pageSize: 10
  order_by: social
  lang: en_US
twikoo:
  envId: null
  region: null
  visitor: false
  option: null
giscus:
  repo: null
  repo_id: null
  category_id: null
  light_theme: light
  dark_theme: dark
  js: null
  option: null
remark42:
  host: null
  siteId: null
  option: null
artalk:
  server: null
  site: null
  visitor: false
  option: null
chat:
  use: null
  rightside_button: false
  button_hide_show: false
chatra:
  id: null
tidio:
  public_key: null
crisp:
  website_id: null
baidu_analytics: null
google_analytics: null
cloudflare_analytics: null
microsoft_clarity: null
umami_analytics:
  enable: false
  serverURL: null
  website_id: null
  option: null
  UV_PV:
    site_uv: false
    site_pv: false
    page_pv: false
    token: null
google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: null
  enable_page_level_ads: true
ad:
  index: null
  aside: null
  post: null
site_verification: null
category_ui: null
tag_ui: null
rounded_corners_ui: true
text_align_justify: false
mask:
  header: true
  footer: true
preloader:
  enable: false
  source: 1
  pace_css_url: null
enter_transitions: true
display_mode: light
beautify:
  enable: false
  field: post
  title_prefix_icon: null
  title_prefix_icon_color: null
font:
  global_font_size: null
  code_font_size: null
  font_family: null
  code_font_family: null
blog_title_font:
  font_link: null
  font_family: null
activate_power_mode:
  enable: false
  colorful: true
  shake: true
  mobile: false
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false
canvas_fluttering_ribbon:
  enable: false
  mobile: false
canvas_nest:
  enable: false
  color: 0,0,255
  opacity: 0.7
  zIndex: -1
  count: 99
  mobile: false
fireworks:
  enable: false
  zIndex: 9999
  mobile: false
click_heart:
  enable: false
  mobile: false
clickShowText:
  enable: false
  text: null
  fontSize: 15px
  random: false
  mobile: false
lightbox: null
series:
  enable: false
  orderBy: title
  order: 1
  number: true
abcjs:
  enable: false
  per_page: true
mermaid:
  enable: false
  code_write: false
  theme:
    light: default
    dark: dark
chartjs:
  enable: false
  fontColor:
    light: rgba(0, 0, 0, 0.8)
    dark: rgba(255, 255, 255, 0.8)
  borderColor:
    light: rgba(0, 0, 0, 0.1)
    dark: rgba(255, 255, 255, 0.2)
  scale_ticks_backdropColor:
    light: transparent
    dark: transparent
note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0
pjax:
  enable: true
  exclude: null
aplayerInject:
  enable: false
  per_page: true
snackbar:
  enable: true
  position: bottom-center
  bg_light: '#49b1f5'
  bg_dark: '#1f1f1f'
instantpage: false
pangu:
  enable: false
  field: site
lazyload:
  enable: true
  field: site
  placeholder: null
  blur: true
pwa:
  enable: false
  manifest: null
  apple_touch_icon: null
  favicon_32_32: null
  favicon_16_16: null
  mask_icon: null
Open_Graph_meta:
  enable: true
  option: null
css_prefix: true
inject:
  head:
    - <link rel="stylesheet" href="/assets/css/index.css">
  bottom:
    - <script src="/assets/js/index.js"></script>
CDN:
  internal_provider: local
  third_party_provider: jsdelivr
  version: false
  custom_format: null
  option: null
