nav:
  logo: null
  display_title: true
  fixed: true
menu:
  首页: / || fas fa-home ||
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友链: /link/ || fas fa-link
highlight_theme: light
highlight_copy: true
highlight_lang: true
highlight_shrink: false
highlight_height_limit: false
code_word_wrap: true
social:
  fas fa-home-alt: https://www.rumbl.top || Home
  fab fa-github: https://github.com/bilirumble || Github
  fas fa-envelope: mailto:bilirumble@outlook.com || EMail
favicon: /assets/images/common/favicon.ico
avatar:
  img: /assets/images/common/avatar.jpg
  effect: false
disable_top_img: false
index_img: https://api.dujin.org/bing/1920.php
default_top_img: https://api.dujin.org/bing/1920.php
archive_img: null
tag_img: null
tag_per_img: null
category_img: null
category_per_img: null
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: both
  default_cover:
    - https://i.loli.net/2020/05/01/gkihqEjXxJ5UZ1C.jpg
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg
error_404:
  enable: true
  subtitle: Page Not Found
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png
post_meta:
  page:
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true
  post:
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true
index_post_content:
  method: 3
  length: 500
anchor:
  button:
    enable: false
    always_show: false
    icon: null
  auto_update: false
photofigcaption: false
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true
post_copyright:
  enable: true
  decode: false
  author_href: https://www.rumbl.top
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
reward:
  enable: false
  QR_code: null
post_edit:
  enable: true
  url: https://github.com/bilirumble/blog/edit/master/source/
related_post:
  enable: true
  limit: 6
  date_type: created
post_pagination: 1
noticeOutdate:
  enable: true
  style: flat
  limit_day: 365
  position: top
  message_prev: 未过时的文章。
  message_next: 该文章可能已过时!
footer:
  owner:
    enable: true
    since: 2019
  custom_text: null
aside:
  enable: true
  hide: false
  button: true
  mobile: false
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: 兴趣使然
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/bilirumble
  card_announcement:
    enable: true
    content: 这里是公告
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order: null
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order: null
  card_tags:
    enable: true
    limit: 40
    color: true
    orderby: random
    order: 1
    sort_order: null
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order: null
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: null
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
runtimeshow:
  enable: true
  publish_date: 2019/1/1 00:00:00
newest_comments:
  enable: true
  sort_order: null
  limit: 6
  storage: 10
  avatar: true
translate:
  enable: true
  default: 繁
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: 繁
  msgToSimplifiedChinese: 簡
readmode: true
darkmode:
  enable: true
  button: true
  autoChangeMode: true
  start: '19:00'
  end: '05:00'
rightside_scroll_percent: false
rightside_item_order:
  enable: false
  hide: null
  show: null
mathjax:
  enable: true
  per_page: false
katex:
  enable: false
  per_page: false
  hide_scrollbar: true
algolia_search:
  enable: false
  hits:
    per_page: 6
local_search:
  enable: true
  preload: true
  top_n_per_article: 1
  unescape: true
  CDN: null
docsearch:
  enable: false
  appId: null
  apiKey: null
  indexName: null
  option: null
addThis:
  enable: false
  pubid: null
sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq
addtoany:
  enable: false
  item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link
comments:
  use: gitalk
  text: true
  lazyload: true
  count: true
  card_post_count: false
disqus:
  shortname: null
  apikey: null
disqusjs:
  shortname: null
  apikey: null
  option: null
livere:
  uid: null
gitalk:
  client_id: f7e15eac4ef4ca140772
  repo: blog
  owner: bilirumble
  admin: bilirumble
  language: zh-CN
  per_page: 25
  distractionFreeMode: false
  pagerDirection: last
  createIssueManually: false
  proxy: https://cs.rumbl.top/github_access_token
  option:
    proxy: https://cs.rumbl.top/github_access_token
valine:
  appId: null
  appKey: null
  avatar: monsterid
  serverURLs: null
  bg: null
  visitor: false
  option: null
waline:
  serverURL: null
  bg: null
  pageview: false
  option: null
utterances:
  repo: null
  issue_term: url
  light_theme: github-light
  dark_theme: photon-dark
facebook_comments:
  app_id: null
  user_id: null
  pageSize: 10
  order_by: social
  lang: zh_CN
twikoo:
  envId: null
  region: null
  visitor: false
  option: null
giscus:
  repo: null
  repo_id: null
  category_id: null
  theme:
    light: light
    dark: dark
  option: null
remark42:
  host: null
  siteId: null
  option: null
artalk:
  server: null
  site: null
  visitor: false
  option: null
chat_btn: false
chat_hide_show: false
chatra:
  enable: false
  id: null
tidio:
  enable: false
  public_key: null
daovoice:
  enable: false
  app_id: null
crisp:
  enable: false
  website_id: null
messenger:
  enable: false
  pageID: null
  lang: zh_CN
baidu_analytics: null
google_analytics: null
cloudflare_analytics: null
microsoft_clarity: null
google_adsense:
  enable: false
  auto_ads: false
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: null
  enable_page_level_ads: true
site_verification: null
index_site_info_top: null
index_top_img_height: null
category_ui: null
tag_ui: null
background: null
footer_bg: true
mask:
  header: true
  footer: true
rightside-bottom: null
enter_transitions: true
activate_power_mode:
  enable: true
  colorful: true
  shake: false
  mobile: true
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true
  mobile: true
canvas_fluttering_ribbon:
  enable: false
  mobile: false
canvas_nest:
  enable: false
  color: 0,0,255
  opacity: 0.7
  zIndex: -1
  count: 99
  mobile: false
fireworks:
  enable: false
  zIndex: 2000
  mobile: false
click_heart:
  enable: false
  mobile: false
ClickShowText:
  enable: false
  text: null
  fontSize: 15px
  random: false
  mobile: false
display_mode: light
beautify:
  enable: true
  field: post
  title-prefix-icon: null
  title-prefix-icon-color: null
font:
  global-font-size: null
  code-font-size: null
  font-family: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato,
    Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: >-
    consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei",
    sans-serif
blog_title_font:
  font_link: null
  font-family: null
hr_icon:
  enable: true
  icon: null
  icon-top: null
subtitle:
  enable: true
  effect: true
  typed_option: null
  loop: true
  source: 1
  sub: null
preloader:
  enable: false
  source: 1
  pace_css_url: null
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true
medium_zoom: false
fancybox: true
abcjs:
  enable: false
  per_page: true
mermaid:
  enable: false
  theme:
    light: default
    dark: dark
note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0
pjax:
  enable: true
  exclude: null
aplayerInject:
  enable: false
  per_page: true
snackbar:
  enable: true
  position: top-center
  bg_light: '#49b1f5'
  bg_dark: '#1f1f1f'
instantpage: true
pangu:
  enable: false
  field: site
lazyload:
  enable: true
  field: site
  placeholder: null
  blur: true
Open_Graph_meta:
  enable: true
  option: null
css_prefix: true
inject:
  head:
    - <link rel="stylesheet" href="/assets/css/index.css">
  bottom:
    - <script src="/assets/js/index.js"></script>
CDN:
  internal_provider: local
  third_party_provider: jsdelivr
  version: false
  custom_format: null
  option: null
